const ErrorCodes = {
    OK: 0,
    UNAUTHENTICATED: 100,
    CONVERSATION_CLOSED: 101,
    SCHEMA_ERROR: 102,
    UNIMPLEMENTED: 103,
    CONVERSATION_NOT_INITIALIZED: 104,
    TIMEOUT: 105,
    USER_INACTIVE: 106,
    INVALID_TOKEN: 107,
    UNKNOWN_ERROR: 108
};


export default ErrorCodes;