const ErrorCodes = {
    OK: 0,
    UNAUTHENTICATED: 100,
    CONVERSATION_CLOSED: 101,
    SCHEMA_ERROR: 102,
    UNIMPLEMENTED: 103,
    CONVERSATION_NOT_INITIALIZED: 104,
    AUTHENTICATION_TIMEOUT: 105,
    AUTH_FAIL_USER_INACTIVE: 106,
    AUTH_FAIL_INVALID_TOKEN: 107,
    INACTIVENESS_TIMEOUT: 108,
    UNKNOWN_ERROR: 109,

};


export default ErrorCodes;